export const DEMO_PLAN = {
  metadata: {
    destino: "Barcelona",
    dias: 5,
    presupuesto: 1200,
    estilo: "cultural",
    generado: new Date().toISOString(),
  },
  itinerario: [
    {
      dia: 1,
      titulo: "Llegada y primer bocado de Barcelona",
      manana: {
        actividades: [
          {
            nombre: "Desayuno en el Mercat de Santa Caterina",
            descripcion: "Mercado con un tejado de mosaico espectacular. Desayuna con los locales en las paradas de la planta baja.",
            duracion: "1 hora",
            precio: "5-8€",
            emoji: "🛒",
            tipo: "gastronomia",
          },
          {
            nombre: "Barrio Gótico a pie",
            descripcion: "Calles medievales con 2000 años de historia. Busca el Pont del Bisbe y la Plaça de Sant Felip Neri.",
            duracion: "2 horas",
            precio: "Gratis",
            emoji: "🏛️",
            tipo: "cultural",
          },
        ],
        consejo: "Lleva calzado cómodo — los adoquines del Gótico son traicioneros con maletas o tacones.",
      },
      tarde: {
        actividades: [
          {
            nombre: "Las Ramblas y Mercado de La Boqueria",
            descripcion: "El mercado más famoso de España. Prueba los zumos frescos y los jamones ibéricos, pero come fuera (es más barato).",
            duracion: "1.5 horas",
            precio: "Gratis (consumir opcional)",
            emoji: "🍊",
            tipo: "gastronomia",
          },
          {
            nombre: "Palau de la Música Catalana",
            descripcion: "Obra maestra modernista de Domènech i Montaner. Incluso si no entras, la fachada exterior justifica el paseo.",
            duracion: "1 hora",
            precio: "20€ (visita guiada) / Gratis exterior",
            emoji: "🎶",
            tipo: "cultural",
          },
        ],
        consejo: "¡Cuidado con los carteristas en Las Ramblas! Bolso cruzado al pecho y nada en los bolsillos traseros.",
      },
      noche: {
        actividades: [
          {
            nombre: "Paseo por el Born y El Raval",
            descripcion: "Los barrios más trendy de Barcelona. Copas en una terraza y ambiente tranquilo para el primer día.",
            duracion: "2 horas",
            precio: "10-15€ en copas",
            emoji: "🌙",
            tipo: "relax",
          },
        ],
        restaurante: {
          nombre: "El Xampanyet",
          tipo: "tapas tradicionales",
          zona: "El Born",
          precio_persona: "15-25€",
          especialidad: "Anchoas con cava artesanal",
          ambiente: "Taberna de toda la vida, íntima y animada",
          emoji: "🥂",
        },
        consejo: "Los barceloneses cenan tarde — llega al restaurante entre las 21h y 22h para sentirte local.",
      },
      coste_estimado: 60,
    },
    {
      dia: 2,
      titulo: "Gaudí en estado puro",
      manana: {
        actividades: [
          {
            nombre: "Sagrada Família",
            descripcion: "La obra maestra inacabada de Gaudí. Reserva con antelación online para evitar las colas eternas.",
            duracion: "2.5 horas",
            precio: "26€ (entrada + torre)",
            emoji: "⛪",
            tipo: "cultural",
          },
          {
            nombre: "Barrio del Eixample",
            descripcion: "Descubre el diseño de cuadrícula única de Barcelona. Busca las esquinas 'chamferradas' (cortadas).",
            duracion: "45 min",
            precio: "Gratis",
            emoji: "🏙️",
            tipo: "cultural",
          },
        ],
        consejo: "Reserva la Sagrada Família online con 48h de antelación mínimo — en verano se agotan las entradas del día.",
      },
      tarde: {
        actividades: [
          {
            nombre: "Casa Batlló o Casa Milà (La Pedrera)",
            descripcion: "Elige una de las dos casas de Gaudí. La Pedrera tiene mejor terraza; Casa Batlló mejor interior.",
            duracion: "1.5 horas",
            precio: "25-35€",
            emoji: "🎨",
            tipo: "cultural",
          },
          {
            nombre: "Paseo de Gracia de compras",
            descripcion: "El boulevard más elegante de Barcelona. Mira escaparates de marcas internacionales y catalanas.",
            duracion: "1 hora",
            precio: "Gratis (comprar opcional)",
            emoji: "🛍️",
            tipo: "compras",
          },
        ],
        consejo: "La tarjeta Articket (35€) da acceso a 6 museos de arte — muy rentable si tienes más de 3 días.",
      },
      noche: {
        actividades: [
          {
            nombre: "Vermouth en la Barceloneta",
            descripcion: "El ritual del vermut del domingo barcelonés. Aceituna, patatas bravas y vermut en el barrio marinero.",
            duracion: "1.5 horas",
            precio: "10-18€",
            emoji: "🍸",
            tipo: "gastronomia",
          },
        ],
        restaurante: {
          nombre: "La Cova Fumada",
          tipo: "cocina marinera tradicional",
          zona: "Barceloneta",
          precio_persona: "20-30€",
          especialidad: "Bombas originales y pescado del día",
          ambiente: "Bar de toda la vida sin carta, sin reservas",
          emoji: "🐟",
        },
        consejo: "La Cova Fumada NO tiene reservas y cierra pronto. Llega antes de las 13h para comer (o es para cenar temprano).",
      },
      coste_estimado: 130,
    },
    {
      dia: 3,
      titulo: "Verde, arte y vistas desde lo alto",
      manana: {
        actividades: [
          {
            nombre: "Park Güell",
            descripcion: "El parque más colorido de Gaudí con vistas panorámicas de Barcelona. La zona monumental tiene entrada.",
            duracion: "2 horas",
            precio: "10€ (zona monumental) / Gratis (parque)",
            emoji: "🌿",
            tipo: "cultural",
          },
          {
            nombre: "Barrio de Gràcia",
            descripcion: "El barrio más bohemio y local de Barcelona. Plazas llenas de terrazas y tiendas independientes.",
            duracion: "1.5 horas",
            precio: "Gratis",
            emoji: "🌸",
            tipo: "cultural",
          },
        ],
        consejo: "Baja desde Park Güell caminando hasta Gràcia (15 min) — el camino por las calles del barrio es precioso.",
      },
      tarde: {
        actividades: [
          {
            nombre: "Museu Picasso",
            descripcion: "La mejor colección de Picasso del mundo, con obras de su etapa juvenil en Barcelona.",
            duracion: "2 horas",
            precio: "14€ / Gratis jueves tarde",
            emoji: "🖼️",
            tipo: "cultural",
          },
          {
            nombre: "Basílica de Santa Maria del Mar",
            descripcion: "La catedral gótica más elegante de Barcelona, construida por el pueblo en el siglo XIV.",
            duracion: "45 min",
            precio: "5€",
            emoji: "⛩️",
            tipo: "cultural",
          },
        ],
        consejo: "El Museu Picasso tiene entrada gratuita los jueves de 17h a 21h — vale la pena planificarlo así.",
      },
      noche: {
        actividades: [
          {
            nombre: "Cócteles en el Skybar del Hotel Arts",
            descripcion: "Las mejores vistas nocturnas de Barcelona desde las alturas. Precio elevado pero la experiencia lo vale.",
            duracion: "1.5 horas",
            precio: "18-25€ por cóctel",
            emoji: "🍹",
            tipo: "relax",
          },
        ],
        restaurante: {
          nombre: "Bar del Pla",
          tipo: "cocina catalana moderna",
          zona: "El Born",
          precio_persona: "25-35€",
          especialidad: "Croquetas de jamón y huevos rotos con foie",
          ambiente: "Animado, lleno de locales, sin reservas",
          emoji: "🍳",
        },
        consejo: "Bar del Pla no acepta reservas — llega a las 20:30h para conseguir mesa sin esperar.",
      },
      coste_estimado: 110,
    },
    {
      dia: 4,
      titulo: "Montjuïc, fútbol y el puerto olímpico",
      manana: {
        actividades: [
          {
            nombre: "Montjuïc en teleférico",
            descripcion: "Sube en el Telefèric de Montjuïc para vistas panorámicas del puerto y la ciudad. Visita el castillo.",
            duracion: "2.5 horas",
            precio: "12.70€ (teleférico ida y vuelta)",
            emoji: "🚡",
            tipo: "aventura",
          },
          {
            nombre: "Fundació Joan Miró",
            descripcion: "Museo dedicado al artista barcelonés más universal, con jardín de esculturas y vistas a la ciudad.",
            duracion: "1.5 horas",
            precio: "14€",
            emoji: "🎭",
            tipo: "cultural",
          },
        ],
        consejo: "Combina el teleférico con la visita al castillo — las vistas del puerto son impresionantes al atardecer.",
      },
      tarde: {
        actividades: [
          {
            nombre: "Camp Nou (visita al museo)",
            descripcion: "El estadio más grande de Europa. Aunque no haya partido, el museo del Barça es imprescindible para los fans.",
            duracion: "2 horas",
            precio: "28€ (museo + campo)",
            emoji: "⚽",
            tipo: "cultural",
          },
          {
            nombre: "Puerto Olímpico y playa",
            descripcion: "El área construida para los JJOO del 92. Paseo marítimo, playas y la escultura del pez de Frank Gehry.",
            duracion: "1.5 horas",
            precio: "Gratis",
            emoji: "🏖️",
            tipo: "relax",
          },
        ],
        consejo: "Si no eres fan del fútbol, sáltate el Camp Nou y aprovecha para hacer una clase de surf en la Barceloneta (~40€).",
      },
      noche: {
        actividades: [
          {
            nombre: "Flamenco en el Palau Dalmases",
            descripcion: "Espectáculo de flamenco en un palacio barroco del siglo XVII. Turístico pero de calidad real.",
            duracion: "1.5 horas",
            precio: "25€ (incluye bebida)",
            emoji: "💃",
            tipo: "cultural",
          },
        ],
        restaurante: {
          nombre: "Bodega Sepúlveda",
          tipo: "bar de vinos con tapas",
          zona: "Eixample Esquerra",
          precio_persona: "20-28€",
          especialidad: "Tabla de quesos catalanes y vinos de la D.O. Penedès",
          ambiente: "Íntimo, acogedor, favorito de los locales",
          emoji: "🍷",
        },
        consejo: "Reserva el flamenco con antelación — las plazas son limitadas y se agotan.",
      },
      coste_estimado: 140,
    },
    {
      dia: 5,
      titulo: "Último día: mercados, souvenirs y adiós",
      manana: {
        actividades: [
          {
            nombre: "Desayuno de despedida en el Café de l'Acadèmia",
            descripcion: "Uno de los cafés más bonitos y auténticos del Gótico. Prueba el pa amb tomàquet con embutidos.",
            duracion: "1 hora",
            precio: "8-12€",
            emoji: "☕",
            tipo: "gastronomia",
          },
          {
            nombre: "Encants Vells (mercado de antigüedades)",
            descripcion: "El mercado de segunda mano más grande de Cataluña, bajo una estructura de espejos espectacular.",
            duracion: "1.5 horas",
            precio: "Gratis",
            emoji: "🗺️",
            tipo: "cultural",
          },
        ],
        consejo: "Compra los souvenirs en el Encants o en las tiendas del Born — evita las tiendas de Las Ramblas (calidad baja, precio alto).",
      },
      tarde: {
        actividades: [
          {
            nombre: "Último paseo por el Born",
            descripcion: "El barrio más auténtico de Barcelona para tomar la última cerveza y comprar algo de diseño local.",
            duracion: "2 horas",
            precio: "Gratis + consumir",
            emoji: "🛶",
            tipo: "relax",
          },
        ],
        consejo: "Guarda el billete del metro — el aeropuerto está a 35 min en L9 Sud (5.50€).",
      },
      noche: {
        actividades: [],
        consejo: "Viaje al aeropuerto con al menos 2.5h de antelación. El Aerobús sale desde Plaça Catalunya cada 5 minutos.",
      },
      coste_estimado: 80,
    },
  ],
  alojamiento: {
    zonas: [
      {
        nombre: "El Born / Sant Pere",
        descripcion: "El barrio más trendy de Barcelona. A 10 min andando de todo: Gótico, Barceloneta y Eixample.",
        ideal_para: "Viajeros culturales y gastronómicos que quieren estar en el centro de la acción",
        nivel_precio: "medio",
        precio_rango: "80-150€/noche",
        emoji: "🏡",
      },
      {
        nombre: "Eixample",
        descripcion: "El corazón modernista de Barcelona. Perfecto para moverse en metro a todos los puntos de interés.",
        ideal_para: "Primeras visitas y viajeros que quieren comodidad y buena oferta de restaurantes",
        nivel_precio: "medio",
        precio_rango: "90-180€/noche",
        emoji: "🏙️",
      },
      {
        nombre: "Barceloneta",
        descripcion: "El barrio marinero junto al mar. Ideal para los que priorizan la playa y el ambiente mediterráneo.",
        ideal_para: "Viajeros de relax y fiesta nocturna en el puerto olímpico",
        nivel_precio: "alto",
        precio_rango: "120-220€/noche",
        emoji: "🏖️",
      },
      {
        nombre: "Gràcia",
        descripcion: "Barrio bohemio y local, lejos del turismo masivo. Ambiente de pueblo dentro de la gran ciudad.",
        ideal_para: "Viajeros que buscan experiencia auténtica alejada del circuito turístico",
        nivel_precio: "económico",
        precio_rango: "55-100€/noche",
        emoji: "🌿",
      },
    ],
    opciones: [
      {
        nombre: "Hotel Neri Relais & Châteaux",
        tipo: "boutique",
        zona: "Barrio Gótico",
        precio_noche: "220-280€",
        descripcion: "Hotel de lujo en un palacio del siglo XVIII en el corazón del Gótico. Terraza con vistas únicas.",
        puntos_fuertes: ["Ubicación inmejorable", "Terraza romántica", "Desayuno incluido"],
        emoji: "🏰",
      },
      {
        nombre: "Praktik Bakery Hotel",
        tipo: "hotel",
        zona: "Eixample",
        precio_noche: "110-150€",
        descripcion: "Hotel boutique con panadería propia en el lobby. Diseño cuidado y ubicación perfecta en el Eixample.",
        puntos_fuertes: ["Desayuno artesanal incluido", "Diseño moderno", "Metro a 2 min"],
        emoji: "🥐",
      },
      {
        nombre: "TOC Hostel Barcelona",
        tipo: "hostal",
        zona: "Las Ramblas",
        precio_noche: "35-70€",
        descripcion: "El mejor hostel de Barcelona según múltiples rankings. Piscina en la terraza, fiestas organizadas.",
        puntos_fuertes: ["Piscina en la azotea", "Gran ambiente social", "Central"],
        emoji: "🎉",
      },
      {
        nombre: "Apartamentos Born Living",
        tipo: "apartamento",
        zona: "El Born",
        precio_noche: "90-130€",
        descripcion: "Apartamentos modernos en el Born. Cocina equipada ideal para grupos o estancias largas.",
        puntos_fuertes: ["Cocina propia (ahorro en comidas)", "Zona premium", "Más espacio"],
        emoji: "🏠",
      },
    ],
    recomendacion: {
      nombre: "Praktik Bakery Hotel",
      motivo: "La mejor relación calidad-precio para un viaje cultural: céntrico, con desayuno artesanal incluido y a 5 min en metro de la Sagrada Família.",
      precio_total_estancia: "~550€ para 4 noches",
    },
  },
  restaurantes: {
    destacados: [
      {
        nombre: "El Xampanyet",
        zona: "El Born",
        tipo: "tapas y cava",
        precio_persona: "15-25€",
        especialidad: "Anchoas con cava artesanal de la casa",
        cuando_ir: "cena",
        ambiente: "Taberna centenaria, íntima y siempre llena",
        por_que: "El sitio favorito de los barceloneses de toda la vida. Auténtico sin concesiones al turismo.",
        emoji: "🥂",
      },
      {
        nombre: "Bar del Pla",
        zona: "El Born",
        tipo: "cocina catalana moderna",
        precio_persona: "25-35€",
        especialidad: "Croquetas de jamón y huevos con foie",
        cuando_ir: "cena",
        ambiente: "Animado, lleno de locales, sin reservas",
        por_que: "El menú del día (13€) es uno de los mejores de Barcelona. Para cenar, pide las croquetas sí o sí.",
        emoji: "🍳",
      },
      {
        nombre: "La Cova Fumada",
        zona: "Barceloneta",
        tipo: "cocina marinera",
        precio_persona: "20-30€",
        especialidad: "Bombas (el plato que inventó este bar en 1945)",
        cuando_ir: "almuerzo",
        ambiente: "Sin carta, sin reservas, sin turistas. Puro bar de barrio.",
        por_que: "Inventaron las 'bombas', la tapa más icónica de Barcelona. Solo van locales.",
        emoji: "💣",
      },
      {
        nombre: "Parking Pizza",
        zona: "Eixample",
        tipo: "pizzería napolitana",
        precio_persona: "18-28€",
        especialidad: "Pizza napolitana con ingredientes catalanes",
        cuando_ir: "cena",
        ambiente: "Moderno y animado, muy popular entre jóvenes locales",
        por_que: "La mejor pizza de Barcelona según los propios barceloneses. Mezcla perfecta de Italia y Cataluña.",
        emoji: "🍕",
      },
      {
        nombre: "Bodega Sepúlveda",
        zona: "Eixample Esquerra",
        tipo: "bar de vinos",
        precio_persona: "20-28€",
        especialidad: "Vinos DO Penedès y quesos catalanes",
        cuando_ir: "copas",
        ambiente: "Íntimo, sin turistas, auténtico bar de vinos",
        por_que: "El secreto mejor guardado del Eixample. Favorito de los sommeliers barceloneses.",
        emoji: "🍷",
      },
    ],
    donde_no_ir: "Evita los restaurantes de Las Ramblas (especialmente los de menú en castellano, inglés y alemán) y los de la Plaça Reial — precios inflados y calidad baja pensada para turistas.",
  },
  tips: {
    transporte: [
      {
        emoji: "🚇",
        titulo: "Tarjeta T-Casual (10 viajes)",
        detalle: "Cuesta 12.15€ y vale para metro, bus, FGC y tranvía. Ahorra un 40% vs billetes sueltos (2.40€/viaje).",
      },
      {
        emoji: "🚲",
        titulo: "Bicing y patinetes eléctricos",
        detalle: "Lime y Bird tienen patinetes por toda la ciudad. 1€ de desbloqueo + 0.25€/min. Perfecto para distancias cortas.",
      },
      {
        emoji: "✈️",
        titulo: "Aeropuerto al centro",
        detalle: "Metro L9 Sud: 5.50€, 35 min hasta Plaça Catalunya. Aerobús: 6.75€, más rápido (30 min) y cómodo con maletas.",
      },
      {
        emoji: "🚌",
        titulo: "Bus Turístic (opcional)",
        detalle: "30€/día. Solo vale la pena si tienes un único día y no quieres pensar en transporte. Con más tiempo, mejor metro.",
      },
    ],
    costumbres: [
      {
        emoji: "🕐",
        titulo: "Los horarios son distintos",
        detalle: "Almuerzo: 14-16h. Cena: 21-23h. Las tiendas cierran de 14h a 17h. No te extrañes si el restaurante está vacío a las 20h.",
      },
      {
        emoji: "💶",
        titulo: "Propinas: opcionales",
        detalle: "En España NO hay cultura de propina obligatoria. Si el servicio fue bueno, redondea o deja 1-2€. No más.",
      },
      {
        emoji: "🗣️",
        titulo: "Catalán y castellano",
        detalle: "El catalán es la lengua oficial. Hablar en castellano está perfectamente bien — nadie se molestará.",
      },
      {
        emoji: "☀️",
        titulo: "Siesta cultural",
        detalle: "Algunos museos y tiendas cierran 2-3h al mediodía. Consulta horarios antes de ir para no llevarte sorpresas.",
      },
    ],
    mejor_epoca: "Primavera (abril-junio) y otoño (sept-oct) son perfectas: clima suave, menos turistas y precios más bajos. El verano (jul-ago) es agotadoramente caluroso y masificado. Evita el Mobile World Congress (febrero) — los hoteles multiplican precios x3.",
    frases_utiles: [
      { es: "Buenos días", local: "Bon dia", pronunciacion: "Bon dí-a" },
      { es: "Gracias", local: "Gràcies", pronunciacion: "Grá-si-es" },
      { es: "¿La cuenta, por favor?", local: "El compte, si us plau", pronunciacion: "El cóm-te, si us plau" },
      { es: "¿Habla español?", local: "Parla castellà?", pronunciacion: "Pár-la cas-te-llá?" },
      { es: "¡Salud!", local: "Salut!", pronunciacion: "Sa-lút" },
    ],
    emergencias: "112 (emergencias general) · 092 (Guardia Urbana de Barcelona) · Hospital Clínic: Carrer de Villarroel, 170",
    apps_recomendadas: [
      "TMB App: metro y bus de Barcelona en tiempo real",
      "Google Maps: funciona perfectamente en Barcelona",
      "TheFork: reservas de restaurante con descuentos",
      "Lime / Bird: patinetes eléctricos",
      "Booking / Airbnb: alojamiento",
    ],
  },
  presupuesto: {
    total_estimado: 1200,
    por_dia: 240,
    desglose: {
      alojamiento: 440,
      comida: 320,
      actividades: 230,
      transporte_local: 80,
      extras: 130,
    },
    consejos_ahorro: [
      "Compra la T-Casual de 10 viajes (12.15€) en lugar de billetes sueltos — ahorras un 40%",
      "Los jueves por la tarde, el Museu Picasso tiene entrada gratuita (17h-21h)",
      "Come el menú del día en lugar de carta: 3 platos + bebida por 12-15€ en el Eixample",
      "Reserva la Sagrada Família y las casas de Gaudí con semanas de antelación online — evitas colas y no hay suplemento",
      "El supermercado Mercadona del Eixample es perfecto para desayunos y meriendas sin gastar en cafeterías",
    ],
  },
};
